# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data1": "00_core.ipynb",
         "data2": "00_core.ipynb",
         "df1": "00_core.ipynb",
         "df2": "00_core.ipynb",
         "curr_dir": "00_core.ipynb",
         "real_path": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://aloiswirth.github.io/quicktest/"

git_url = "https://github.com/aloiswirth/quicktest/tree/main/"

def custom_doc_links(name): return None
